import './globals.css'
import { 
  //Inter, 
  Courier_Prime
 } from 'next/font/google';
import Navbar from './components/Navbar';

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
// })
const courier = Courier_Prime({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={courier.className}>
      <head>
        <title>Jiří Vecko</title>
      </head>
      <body className="min-h-full w-full bg-gradient-to-b from-black to-slate-500">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
